name: Build & Push Nitro CLI Container

on:
  workflow_dispatch:

  push:
    branches:
      - main

jobs:
  build-nitro-cli:
    runs-on: ubuntu-latest

    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read  # This is required for actions/checkout

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Authenticate to AWS
        uses: aws-actions/configure-aws-credentials@v5
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::077296892761:role/EnclaverGitHubActionsRegistryPush

      - name: Configure AWS Docker Auth
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          registry-type: public

      - name: Build Nitro CLI Image
        uses: docker/build-push-action@v3
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: public.ecr.aws/s2t1d4c6/enclaver-io/nitro-cli:latest
