name: Build & Push Nitro CLI Container

on:
  workflow_dispatch:

  push:
    branches:
      - main

jobs:
  build-nitro-cli:
    runs-on: ubuntu-latest

    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read  # This is required for actions/checkout

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Authenticate to Google Cloud
        uses: 'google-github-actions/auth@v0'
        with:
          workload_identity_provider: 'projects/77991489452/locations/global/workloadIdentityPools/gh-actions-identity-pool/providers/gh-actions-identity-provider'
          service_account: 'github-actions-service-account@edgebit-containers.iam.gserviceaccount.com'

      - name: Configure GCP Docker Auth
        run: |
          gcloud auth configure-docker us-docker.pkg.dev

      - name: Build Nitro CLI Image
        uses: docker/build-push-action@v3
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: us-docker.pkg.dev/edgebit-containers/containers/nitro-cli:latest
